const data = [
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question: "Who created the digital distribution platform Steam?",
		correct_answer: "Valve",
		options: ["Valve", "Electronic Arts", "Ubisoft", "Pixeltail Games"],
	},
	{
		category: "Entertainment: Books",
		type: "multiple",
		difficulty: "easy",
		question:
			"George Orwell wrote this book, which is often considered a statement on government oversight.",
		correct_answer: "1984",
		options: [
			"To Kill a Mockingbird",
			"The Old Man and the Sea",
			"Catcher and the Rye",
			"1984",
		],
	},
	{
		category: "Geography",
		type: "multiple",
		difficulty: "medium",
		question: "What is the capital of Peru?",
		correct_answer: "Lima",
		options: ["Lima", "Buenos Aires", "Santiago", "Montevideo"],
	},
	{
		category: "History",
		type: "boolean",
		difficulty: "hard",
		question: "Japan was part of the Allied Powers during World War I.",
		correct_answer: "True",
		options: ["True", "False"],
	},
	{
		category: "Geography",
		type: "boolean",
		difficulty: "medium",
		question: "Seoul is the capital of North Korea.",
		correct_answer: "False",
		options: ["True", "False"],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "easy",
		question:
			"Which movie contains the quote, &quot;Say hello to my little friend!&quot;?",
		correct_answer: "Scarface",
		options: ["Goodfellas", "Scarface", "Reservoir Dogs", "Heat"],
	},
	{
		category: "Entertainment: Comics",
		type: "multiple",
		difficulty: "easy",
		question:
			"Who is the creator of the comic series &quot;The Walking Dead&quot;?",
		correct_answer: "Robert Kirkman",
		options: [
			"Robert Kirkman",
			"Malcolm Wheeler-Nicholson",
			"Stan Lee",
			"Robert Crumb",
		],
	},
	{
		category: "Entertainment: Books",
		type: "multiple",
		difficulty: "medium",
		question:
			"By what nickname is Jack Dawkins known in the Charles Dickens novel, &#039;Oliver Twist&#039;?",
		correct_answer: "The Artful Dodger",
		options: ["Mr. Fang", "Fagin", "The Artful Dodger", "Bull&rsquo;s-eye"],
	},
	{
		category: "Animals",
		type: "multiple",
		difficulty: "medium",
		question: "Cashmere is the wool from which kind of animal?",
		correct_answer: "Goat",
		options: ["Llama", "Sheep", "Goat", "Camel"],
	},
	{
		category: "Sports",
		type: "multiple",
		difficulty: "easy",
		question: "In baseball, how many fouls are an out?",
		correct_answer: "0",
		options: ["5", "3", "0", "2"],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "easy",
		question:
			"Which of the following ancient peoples was NOT classified as Hellenic (Greek)?",
		correct_answer: "Illyrians",
		options: ["Achaeans", "Ionians", "Illyrians", "Dorians"],
	},
	{
		category: "Vehicles",
		type: "multiple",
		difficulty: "medium",
		question:
			"Complete the following analogy: Audi is to Volkswagen as Infiniti is to ?",
		correct_answer: "Nissan",
		options: ["Honda", "Subaru", "Hyundai", "Nissan"],
	},
	{
		category: "Science: Computers",
		type: "multiple",
		difficulty: "medium",
		question:
			"What did the name of the Tor Anonymity Network orignially stand for?",
		correct_answer: "The Onion Router",
		options: [
			"The Only Router",
			"The Ominous Router",
			"The Onion Router",
			"The Orange Router",
		],
	},
	{
		category: "General Knowledge",
		type: "multiple",
		difficulty: "hard",
		question: "Sciophobia is the fear of what?",
		correct_answer: "Shadows",
		options: ["Eating", "Shadows", "Transportation", "Bright lights"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "easy",
		question: "Who is the lead singer of the British pop rock band Coldplay?",
		correct_answer: "Chris Martin",
		options: [
			"Chris Martin",
			"Jonny Buckland",
			"Will Champion",
			"Guy Berryman",
		],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "medium",
		question:
			"What was another suggested name for, the 1985 film, Back to the Future?",
		correct_answer: "Spaceman From Pluto",
		options: [
			"Spaceman From Pluto",
			"Hill Valley Time Travelers",
			"The Lucky Man",
			"The Time Travelers",
		],
	},
	{
		category: "Vehicles",
		type: "multiple",
		difficulty: "medium",
		question: "What do the 4 Rings in Audi&#039;s Logo represent?",
		correct_answer: "Previously independent automobile manufacturers",
		options: [
			"Countries in which Audi makes the most sales",
			"Main cities vital to Audi",
			"Previously independent automobile manufacturers",
			"States in which Audi makes the most sales",
		],
	},
	{
		category: "Science & Nature",
		type: "boolean",
		difficulty: "medium",
		question:
			"Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.",
		correct_answer: "False",
		options: ["True", "False"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question:
			"In Need for Speed: Most Wanted (2005), what was the name of the main antagonist?",
		correct_answer: "Clarence &quot;Razor&quot; Callahan",
		options: [
			"Toru &quot;Bull&quot; Sato",
			"Hector &quot;Ming&quot; Domingo",
			"Karl &quot;Baron&quot; Smit",
			"Clarence &quot;Razor&quot; Callahan",
		],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "medium",
		question:
			"During the game&#039;s development, what was the first ever created Pok&eacute;mon?",
		correct_answer: "Rhyhorn",
		options: ["Arceus", "Rhyhorn", "Mew", "Bulbasaur"],
	},
	{
		category: "Entertainment: Television",
		type: "multiple",
		difficulty: "easy",
		question:
			"In the television show Breaking Bad, what is the street name of Walter and Jesse&#039;s notorious product?",
		correct_answer: "Blue Sky",
		options: ["Rock Candy", "Pure Glass", "Blue Sky", "Baby Blue"],
	},
	{
		category: "Entertainment: Cartoon & Animations",
		type: "multiple",
		difficulty: "medium",
		question: "What is the cartoon character, Andy Capp, known as in Germany?",
		correct_answer: "Willi Wakker",
		options: [
			"Willi Wakker",
			"Dick Tingeler",
			"Rod Tapper",
			"Helmut Schmacker",
		],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "medium",
		question:
			"In The Lord of the Rings: The Fellowship of the Ring, which one of the following characters from the book was left out of the film?",
		correct_answer: "Tom Bombadil",
		options: ["Celeborn", "Strider", "Barliman Butterbur", "Tom Bombadil"],
	},
	{
		category: "Entertainment: Television",
		type: "multiple",
		difficulty: "easy",
		question:
			"In the show &quot;Tengen Toppa Gurren Lagann&quot; what is the name of the character who force everyone to live underground?",
		correct_answer: "Lordgenome",
		options: ["King Loname", "Lordgenome", "Lord Genome", "Kingloname"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "medium",
		question:
			"In the game &quot;Terraria&quot;, which of these bosses are pre-hardmode bosses?",
		correct_answer: "Eye of Cthulhu",
		options: ["The Destroyer", "Eye of Cthulhu", "Skeletron Prime", "Plantera"],
	},
	{
		category: "Entertainment: Music",
		type: "boolean",
		difficulty: "easy",
		question: "A Saxophone is a brass instrument.",
		correct_answer: "False",
		options: ["True", "False"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "hard",
		question:
			"In &quot;Halo&quot;, what is the name of the planet which Installation 04 orbits?",
		correct_answer: "Threshold",
		options: ["Sanghelios", "Te", "Threshold", "Substance"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "medium",
		question: "How many members are in the Japanese rock band SCANDAL?",
		correct_answer: "4",
		options: ["2", "4", "18", "5"],
	},
	{
		category: "Geography",
		type: "boolean",
		difficulty: "medium",
		question: "Norway has a larger land area than Sweden.",
		correct_answer: "False",
		options: ["True", "False"],
	},
	{
		category: "Science: Computers",
		type: "multiple",
		difficulty: "easy",
		question: "This mobile OS held the largest market share in 2012.",
		correct_answer: "iOS",
		options: ["Android", "iOS", "BlackBerry", "Symbian"],
	},
	{
		category: "Entertainment: Books",
		type: "multiple",
		difficulty: "easy",
		question: "What is the name of Sherlock Holmes&#039;s brother?",
		correct_answer: "Mycroft Holmes",
		options: [
			"Mycroft Holmes",
			"Martin Holmes",
			"Mederi Holmes",
			"Herbie Hancock Holmes",
		],
	},
	{
		category: "Entertainment: Cartoon & Animations",
		type: "multiple",
		difficulty: "hard",
		question:
			"In &quot;Rick and Morty&quot;, from which dimension do Rick and Morty originate from?",
		correct_answer: "C-137",
		options: ["J1977", "C-137", "C500-a", "C-136"],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "hard",
		question:
			"According to &quot;Star Wars&quot; lore, which planet does Obi-Wan Kenobi come from?",
		correct_answer: "Stewjon",
		options: ["Stewjon", "Tatooine", "Naboo", "Alderaan"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "hard",
		question:
			"Electronic artists Boys Noize and Skrillex have collaborated and released tracks under what name?",
		correct_answer: "Dog Blood",
		options: ["Jack &Uuml;", "Noisia", "Dog Blood", "What So Not"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "hard",
		question:
			"What was the name of Sonic the Hedgehog&#039;s original human girlfriend?",
		correct_answer: "Madonna",
		options: ["Nina", "Madonna", "Sierra", "Celeste"],
	},
	{
		category: "Entertainment: Japanese Anime & Manga",
		type: "multiple",
		difficulty: "hard",
		question: "Which animation studio animated &quot;Hidamari Sketch&quot;?",
		correct_answer: "Shaft",
		options: ["Production I.G", "Shaft", "Trigger", "Kyoto Animation"],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "medium",
		question: "In Mulan (1998), who is the leader of the Huns?",
		correct_answer: "Shan Yu",
		options: ["Fa Zhou", "Li Shang", "Shan Yu", "Chien-Po"],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "medium",
		question: "What is Lilo&#039;s last name from Lilo and Stitch?",
		correct_answer: "Pelekai",
		options: ["Ku\u02bbulei", "Kealoha", "Anoa\u02bbi", "Pelekai"],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "hard",
		question:
			"What was the last colony the UK ceded marking the end of the British Empire?",
		correct_answer: "Hong Kong",
		options: ["Ireland", "Hong Kong", "Australia", "India"],
	},
	{
		category: "Entertainment: Television",
		type: "multiple",
		difficulty: "easy",
		question:
			"On the NBC show Community, whose catch-phrase was &quot;Pop! Pop!&quot;?",
		correct_answer: "Magnitude",
		options: ["Magnitude", "Leonard", "Star Burns", "Senoir Chang"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question:
			"What is the name of the main protagonist in &quot;Xenoblade Chronicles&quot;?",
		correct_answer: "Shulk",
		options: ["Fiora", "Dunban", "Reyn", "Shulk"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "easy",
		question:
			"&quot;Doctor Jones&quot;, &quot;Turn Back Time&quot; and &quot;Barbie Girl&quot; were UK number ones for which Eurodance group?",
		correct_answer: "Aqua",
		options: ["Eiffel 65", "Vengaboys", "Aqua", "Sash!"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "medium",
		question: "Who was walking like an Egyptian in 1981?",
		correct_answer: "The Bangles",
		options: ["The Bangles", "The Ocean Blue", "R.E.M.", "The Connells"],
	},
	{
		category: "Sports",
		type: "multiple",
		difficulty: "easy",
		question:
			"What is the most common type of pitch thrown by pitchers in baseball?",
		correct_answer: "Fastball",
		options: ["Palmball", "Screwball", "Fastball", "Slowball"],
	},
	{
		category: "Sports",
		type: "multiple",
		difficulty: "easy",
		question:
			"Who is often called &quot;the Maestro&quot; in the men&#039;s tennis circuit?",
		correct_answer: "Roger Federer",
		options: ["Bill Tilden", "Roger Federer", "Boris Becker", "Pete Sampras"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question:
			"In &quot;Pheonix Wright: Ace Attorney&quot; which character is the District Chief of Police?",
		correct_answer: "Damon Gant",
		options: ["Miles Edgeworth", "Damon Gant", "Mike Meekins", "Lana Skye"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question:
			"What is the name of the adventurer you meet at the mines in Stardew Valley?",
		correct_answer: "Marlon",
		options: ["Marnie", "Morris", "Marvin", "Marlon"],
	},
	{
		category: "Geography",
		type: "multiple",
		difficulty: "medium",
		question: "What is the longest river in Europe?",
		correct_answer: "Volga",
		options: ["Thames", "Danube", "Rhine", "Volga"],
	},
	{
		category: "General Knowledge",
		type: "multiple",
		difficulty: "medium",
		question: "The Mexican Beer &quot;Corona&quot; is what type of beer?",
		correct_answer: "Pale Lager",
		options: ["Baltic Porter", "Pale Lager", "Pilfsner", "India Pale Ale"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "medium",
		question:
			"In Pokemon Diamond, Pearl and Platinum, where can a Munchlax be found?",
		correct_answer: "Honey Trees",
		options: [
			"Trading with an NPC",
			"Wayward Cave",
			"Grass on Route 209",
			"Honey Trees",
		],
	},
	{
		category: "General Knowledge",
		type: "multiple",
		difficulty: "hard",
		question:
			"Electronic music producer Kygo&#039;s popularity skyrocketed after a certain remix. Which song did he remix?",
		correct_answer: "Ed Sheeran - I See Fire",
		options: [
			"Ed Sheeran - I See Fire",
			"Marvin Gaye - Sexual Healing",
			"Coldplay - Midnight",
			"a-ha - Take On Me",
		],
	},
	{
		category: "Science: Computers",
		type: "multiple",
		difficulty: "easy",
		question:
			"Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?",
		correct_answer: "Apple",
		options: ["Microsoft", "Atari", "Commodore", "Apple"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "medium",
		question: "What was the character Kirby originally going to be named?",
		correct_answer: "Popopo",
		options: ["Prince Puff", "Dedede", "Waddle Dee", "Popopo"],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "easy",
		question: "When was the movie &#039;Con Air&#039; released?",
		correct_answer: "1997",
		options: ["1985", "1999", "1990", "1997"],
	},
	{
		category: "Entertainment: Books",
		type: "multiple",
		difficulty: "easy",
		question:
			"Which famous book is sub-titled &#039;The Modern Prometheus&#039;?",
		correct_answer: "Frankenstein",
		options: [
			"The Legend of Sleepy Hollow",
			"Frankenstein",
			"Dracula",
			"The Strange Case of Dr. Jekyll and Mr. Hyde ",
		],
	},
	{
		category: "Entertainment: Cartoon & Animations",
		type: "multiple",
		difficulty: "easy",
		question:
			"The song &#039;Little April Shower&#039; features in which Disney cartoon film?",
		correct_answer: "Bambi",
		options: ["Bambi", "Cinderella", "The Jungle Book", "Pinocchio"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "easy",
		question:
			"Who had a 1969 top 5 hit with the song,  &#039;A Boy Named Sue&#039;?",
		correct_answer: "Johnny Cash",
		options: [
			"Kris Kristofferson",
			"Johnny Cash",
			"Bob Dylan",
			"Willie Nelson",
		],
	},
	{
		category: "Entertainment: Video Games",
		type: "boolean",
		difficulty: "easy",
		question:
			"The main character in the &quot;Half-Life&quot; franchise is named Morgan Freeman.",
		correct_answer: "False",
		options: ["True", "False"],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "easy",
		question: "Which German field marshal was known as the `Desert Fox`?",
		correct_answer: "Erwin Rommel",
		options: [
			"Wolfram Freiherr von Richthofen",
			"Wilhelm List",
			"Erwin Rommel",
			"Ernst Busch",
		],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question:
			"Which of these is NOT a map included in the game Counter-Strike: Global Offensive?",
		correct_answer: "Oilrig",
		options: ["Oilrig", "Assault", "Mirage", "Cache"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "medium",
		question:
			"Which of these games was the earliest known first-person shooter with a known time of publication?",
		correct_answer: "Spasim",
		options: ["Doom", "Quake", "Wolfenstein", "Spasim"],
	},
	{
		category: "Geography",
		type: "boolean",
		difficulty: "easy",
		question:
			"San Marino is the only country completely surrounded by another country.",
		correct_answer: "False",
		options: ["False", "True"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "medium",
		question: "What is the original name of Final Fantasy XV?",
		correct_answer: "Final Fantasy Versus XIII",
		options: [
			"Final Fantasy XVI",
			"Final Fantasy XIII-3",
			"Final Fantasy: Reborn",
			"Final Fantasy Versus XIII",
		],
	},
	{
		category: "Entertainment: Comics",
		type: "boolean",
		difficulty: "hard",
		question:
			"In the comic book &quot;Archie&quot;, Betty is friends with Veronica because she is rich.",
		correct_answer: "False",
		options: ["True", "False"],
	},
	{
		category: "Geography",
		type: "multiple",
		difficulty: "easy",
		question:
			"What name was historically used for the Turkish city currently known as Istanbul?",
		correct_answer: "Constantinople",
		options: [
			"H&uuml;davendigar",
			"Constantinople",
			"S&ouml;\u011f&uuml;t",
			"Adrianople",
		],
	},
	{
		category: "Sports",
		type: "multiple",
		difficulty: "medium",
		question: "Which country is hosting the 2022 FIFA World Cup?",
		correct_answer: "Qatar",
		options: ["Vietnam", "Uganda", "Bolivia", "Qatar"],
	},
	{
		category: "General Knowledge",
		type: "boolean",
		difficulty: "medium",
		question:
			"The average woman is 5 inches / 13 centimeters shorter than the average man.",
		correct_answer: "True",
		options: ["False", "True"],
	},
	{
		category: "Politics",
		type: "boolean",
		difficulty: "easy",
		question: "Denmark has a monarch.",
		correct_answer: "True",
		options: ["False", "True"],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "hard",
		question:
			"In 2012, which movie won every category in the 32nd &quot;Golden Raspberry Awards&quot;?",
		correct_answer: "Jack and Jill",
		options: [
			"Thor",
			"Jack and Jill",
			"The Girl with the Dragon Tattoo",
			"The King&#039;s Speech",
		],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question: "What year did the game &quot;Overwatch&quot; enter closed beta?",
		correct_answer: "2015",
		options: ["2013", "2011", "2015", "2016"],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "hard",
		question:
			"Which one of these rulers did not belong to the Habsburg dynasty?",
		correct_answer: "Philip V",
		options: ["Francis Joseph", "Philip V", "Philip II", "Charles V"],
	},
	{
		category: "Entertainment: Television",
		type: "multiple",
		difficulty: "medium",
		question:
			"In Breaking Bad, the initials W.W. refer to which of the following?",
		correct_answer: "Walter White",
		options: ["Willy Wonka", "Wally Walrus", "William Wolf", "Walter White"],
	},
	{
		category: "Vehicles",
		type: "multiple",
		difficulty: "hard",
		question: "Which one of these chassis codes are used by BMW 3-series?",
		correct_answer: "E46",
		options: ["F10", "E46", "E85", "E39"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "medium",
		question:
			"Which of these is NOT a faction included in the game Counter-Strike: Global Offensive?",
		correct_answer: "BOPE",
		options: ["BOPE", "Phoenix Connexion", "Elite Crew", "GSG-9"],
	},
	{
		category: "Science: Mathematics",
		type: "multiple",
		difficulty: "medium",
		question:
			"What is the alphanumeric representation of the imaginary number?",
		correct_answer: "i",
		options: ["n", "i", "x", "e"],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "hard",
		question:
			"Who invented the &quot;Flying Shuttle&quot; in 1738; one of the key developments in the industrialization of weaving?",
		correct_answer: "John Kay",
		options: [
			"John Deere",
			"James Hargreaves",
			"Richard Arkwright",
			"John Kay",
		],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "easy",
		question:
			"Sting, the lead vocalist of The Police, primarily plays what instrument?",
		correct_answer: "Bass Guitar",
		options: ["Guitar", "Bass Guitar", "Drums", "Keyboards"],
	},
	{
		category: "Science: Computers",
		type: "boolean",
		difficulty: "easy",
		question:
			"In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
		correct_answer: "True",
		options: ["True", "False"],
	},
	{
		category: "Entertainment: Japanese Anime & Manga",
		type: "multiple",
		difficulty: "easy",
		question:
			"In &quot;The Melancholy of Haruhi Suzumiya&quot; series, the SOS Brigade club leader is unknowingly treated as a(n) __ by her peers.",
		correct_answer: "God",
		options: ["Esper", "Alien", "Time Traveler", "God"],
	},
	{
		category: "General Knowledge",
		type: "boolean",
		difficulty: "easy",
		question: "The Lego Group was founded in 1932.",
		correct_answer: "True",
		options: ["False", "True"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question:
			"In what year was the first &quot;Mass Effect&quot; game released?",
		correct_answer: "2007",
		options: ["2008", "2007", "2009", "2010"],
	},
	{
		category: "Entertainment: Video Games",
		type: "boolean",
		difficulty: "easy",
		question:
			"The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
		correct_answer: "True",
		options: ["True", "False"],
	},
	{
		category: "Geography",
		type: "multiple",
		difficulty: "easy",
		question: "What is the capital of the US State of New York?",
		correct_answer: "Albany",
		options: ["Rochester", "Buffalo", "New York", "Albany"],
	},
	{
		category: "Geography",
		type: "multiple",
		difficulty: "hard",
		question: "What is the second-largest city in Lithuania?",
		correct_answer: "Kaunas",
		options: ["Klaip\u0117da", "Panev\u0117\u017eys", "Vilnius", "Kaunas"],
	},
	{
		category: "Celebrities",
		type: "multiple",
		difficulty: "medium",
		question:
			"Which radio personality calls himself &quot;The King of All Media&quot;?",
		correct_answer: "Howard Stern",
		options: ["Rush Limbaugh", "Howard Stern", "Pete Tong", "Ryan Seacrest"],
	},
	{
		category: "Entertainment: Cartoon & Animations",
		type: "multiple",
		difficulty: "medium",
		question:
			"Which one of these cartoon characters is NOT voiced by Rob Paulsen?",
		correct_answer: "Max Tennyson (Ben 10)",
		options: [
			"The Mask (The Mask, TV Series)",
			"Yakko Warner (Animaniacs)",
			"Carl Wheezer (Jimmy Neutron)",
			"Max Tennyson (Ben 10)",
		],
	},
	{
		category: "Entertainment: Japanese Anime & Manga",
		type: "multiple",
		difficulty: "medium",
		question: "Who is the creator of the manga series &quot;One Piece&quot;?",
		correct_answer: "Eiichiro Oda",
		options: [
			"Yoshihiro Togashi",
			"Masashi Kishimoto",
			"Eiichiro Oda",
			"Hayao Miyazaki",
		],
	},
	{
		category: "Politics",
		type: "multiple",
		difficulty: "medium",
		question:
			"Who was elected leader of the UK Labour Party in September 2015?",
		correct_answer: "Jeremy Corbyn",
		options: ["Ed Miliband", "Theresa May", "Jeremy Corbyn", "David Cameron"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "hard",
		question:
			"Which of these characters wasn&#039;t a villian in Club Penguin?",
		correct_answer: "The Director",
		options: [
			"Herbert P. Bear",
			"Tusk",
			"The Director",
			"Ultimate Proto-Bot 10000",
		],
	},
	{
		category: "General Knowledge",
		type: "multiple",
		difficulty: "medium",
		question:
			"What was the original name of the search engine &quot;Google&quot;?",
		correct_answer: "BackRub",
		options: ["BackRub", "CatMassage", "SearchPro", "Netscape Navigator"],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "hard",
		question: "In Big Hero 6, what were Baymax&#039;s motions modeled after?",
		correct_answer: "Baby penguins",
		options: ["Baby ostriches", "Baby bears", "Baby penguins", "Baby monkeys"],
	},
	{
		category: "Entertainment: Comics",
		type: "multiple",
		difficulty: "hard",
		question:
			"When Batman trolls the online chat rooms, what alias does he use?",
		correct_answer: "JonDoe297",
		options: ["BW1129", "iAmBatman", "BWayne13", "JonDoe297"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "medium",
		question: "From which country does the piano originate?",
		correct_answer: "Italy",
		options: ["Austria", "France", "Italy", "Germany"],
	},
	{
		category: "Science & Nature",
		type: "multiple",
		difficulty: "medium",
		question:
			"Which of the following men does not have a chemical element named after him?",
		correct_answer: "Sir Isaac Newton",
		options: [
			"Albert Einstein",
			"Sir Isaac Newton",
			"Niels Bohr",
			"Enrico Fermi",
		],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "medium",
		question:
			"The &#039;In the Flesh&#039; tour was used in support of what Pink Floyd album?",
		correct_answer: "Animals",
		options: ["Wish You Were Here", "The Final Cut", "Animals", "The Wall"],
	},
	{
		category: "Sports",
		type: "multiple",
		difficulty: "easy",
		question: "What team did England beat to win in the 1966 World Cup final?",
		correct_answer: "West Germany",
		options: ["Brazil", "West Germany", "Soviet Union", "Portugal"],
	},
	{
		category: "Geography",
		type: "multiple",
		difficulty: "medium",
		question: "What is the longest river in Europe?",
		correct_answer: "Volga",
		options: ["Danube", "Rhine", "Volga", "Thames"],
	},
	{
		category: "Science & Nature",
		type: "multiple",
		difficulty: "hard",
		question:
			"What was the first organic compound to be synthesized from inorganic compounds?",
		correct_answer: "Urea",
		options: ["Urea", "Propane", "Ethanol", "Formaldehyde"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "medium",
		question: "How many stars are there to collect in Super Mario 64?",
		correct_answer: "120",
		options: ["120", "100", "60", "80"],
	},
	{
		category: "Entertainment: Television",
		type: "multiple",
		difficulty: "easy",
		question: "In the show &quot;Futurama&quot; what is Fry&#039;s full name?",
		correct_answer: "Philip J. Fry",
		options: [
			"Fry J. Philip",
			"Philip J. Fry",
			"Fry Rodr&iacute;guez",
			"Fry Philip",
		],
	},
	{
		category: "Entertainment: Cartoon & Animations",
		type: "multiple",
		difficulty: "easy",
		question: "In South Park, what is Stan&#039;s surname?",
		correct_answer: "Marsh",
		options: ["Tweak", "Stotch", "Marsh", "Broflovski"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "medium",
		question:
			"Which band had hits in 1975 with the songs, &#039;One Of These Nights&#039; &amp; &#039;Lyin Eyes&#039;?",
		correct_answer: "The Eagles",
		options: [
			"The Eagles",
			"Fleetwood Mac",
			"The Doobie Brothers",
			"Fools Gold",
		],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "medium",
		question:
			"Which American family band had a 1986 top 10 hit with the song &#039;Crush On You&#039;?",
		correct_answer: "The Jets",
		options: ["The Jets", "DeBarge", "The Jacksons", "The Cover Girls"],
	},
	{
		category: "Geography",
		type: "boolean",
		difficulty: "medium",
		question: "Seoul is the capital of North Korea.",
		correct_answer: "False",
		options: ["True", "False"],
	},
	{
		category: "General Knowledge",
		type: "boolean",
		difficulty: "medium",
		question: "Coca-Cola&#039;s original colour was green.",
		correct_answer: "False",
		options: ["False", "True"],
	},
	{
		category: "Art",
		type: "multiple",
		difficulty: "hard",
		question: "What French sculptor designed the Statue of Liberty? ",
		correct_answer: "Fr&eacute;d&eacute;ric Auguste Bartholdi",
		options: [
			"Jean-L&eacute;on G&eacute;r&ocirc;me",
			"Henri Matisse",
			"Fr&eacute;d&eacute;ric Auguste Bartholdi",
			"Auguste Rodin",
		],
	},
	{
		category: "Science & Nature",
		type: "multiple",
		difficulty: "medium",
		question: "Which element has the atomic number of 7?",
		correct_answer: "Nitrogen",
		options: ["Nitrogen", "Neon", "Oxygen", "Hydrogen"],
	},
	{
		category: "Geography",
		type: "multiple",
		difficulty: "hard",
		question:
			"The mountainous Khyber Pass connects which of the two following countries?",
		correct_answer: "Afghanistan and Pakistan",
		options: [
			"Pakistan and India",
			"Tajikistan and Kyrgyzstan",
			"Afghanistan and Pakistan",
			"India and Nepal",
		],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question: "Who is the main character in &quot;The Stanley Parable&quot;?",
		correct_answer: "Stanley",
		options: ["Stanley", "The Adventure Line", "The Narrator", "The Boss"],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "easy",
		question: "Which of these countries remained neutral during World War II?",
		correct_answer: "Switzerland",
		options: ["Italy", "Switzerland", "France", "United Kingdom"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question: "What ingredient is NOT used to craft a cake in Minecraft?",
		correct_answer: "Bread",
		options: ["Bread", "Wheat", "Milk", "Egg"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "medium",
		question: "How many classes are there in Team Fortress 2?",
		correct_answer: "9",
		options: ["7", "10", "8", "9"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "easy",
		question:
			"In the 2002 video game &quot;Kingdom Hearts&quot;, how many Keyblades are usable?",
		correct_answer: "18",
		options: ["18", "15", "16", "13"],
	},
	{
		category: "Science & Nature",
		type: "multiple",
		difficulty: "hard",
		question: "Folic acid is the synthetic form of which vitamin?",
		correct_answer: "Vitamin B",
		options: ["Vitamin B", "Vitamin D", "Vitamin C", "Vitamin A"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "hard",
		question:
			"Which of these is NOT a song featured on the Lockjaw EP released in 2013 by Flume &amp; Chet Faker?",
		correct_answer: "Left Alone",
		options: [
			"Drop The Game",
			"What About Us",
			"This Song Is Not About A Girl",
			"Left Alone",
		],
	},
	{
		category: "Politics",
		type: "boolean",
		difficulty: "easy",
		question:
			"Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
		correct_answer: "False",
		options: ["False", "True"],
	},
	{
		category: "Entertainment: Video Games",
		type: "boolean",
		difficulty: "hard",
		question:
			"In &quot;Portal 2&quot;, Cave Johnson started out Aperture Science as a shower curtain company.",
		correct_answer: "True",
		options: ["False", "True"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "medium",
		question:
			"In Call of Duty: United Offensive, what two soldiers share a name of a video game character?",
		correct_answer: "Gordon &amp; Freeman",
		options: [
			"Sam &amp; Fisher",
			"Dig &amp; Dug",
			"Nathan &amp; Drake",
			"Gordon &amp; Freeman",
		],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "medium",
		question:
			"What was another suggested name for, the 1985 film, Back to the Future?",
		correct_answer: "Spaceman From Pluto",
		options: [
			"The Lucky Man",
			"Hill Valley Time Travelers",
			"The Time Travelers",
			"Spaceman From Pluto",
		],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "medium",
		question: "What nationality was sultan Saladin?",
		correct_answer: "Kurdish",
		options: ["Syrian", "Kurdish", "Egyptian", "Arab"],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "hard",
		question:
			"The Hagia Sophia was commissioned by which emperor of the Byzantine Empire?",
		correct_answer: "Justinian I",
		options: [
			"Theodosius the Great",
			"Constantine IV",
			"Justinian I",
			"Arcadius",
		],
	},
	{
		category: "Entertainment: Board Games",
		type: "multiple",
		difficulty: "hard",
		question:
			"On a standard Monopoly board, how much do you have to pay for Tennessee Ave?",
		correct_answer: "$180",
		options: ["$160", "$200", "$220", "$180"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "hard",
		question:
			"This album, now considered to be one of the greatest of all time, was a commercial failure when it was released.",
		correct_answer: "The Velvet Underground and Nico",
		options: [
			"The Velvet Underground and Nico",
			"Abbey Road",
			"Pet Sounds",
			"Led Zeppelin IV",
		],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "medium",
		question: "What is Brian May&#039;s guitar called?",
		correct_answer: "Red Special",
		options: ["Yellow Special", "Red Special", "Green Special", "Blue Special"],
	},
	{
		category: "General Knowledge",
		type: "multiple",
		difficulty: "medium",
		question: "Amsterdam Centraal station is twinned with what station?",
		correct_answer: "London Liverpool Street",
		options: [
			"London Liverpool Street",
			"Frankfurt (Main) Hauptbahnhof",
			"Paris Gare du Nord",
			"Brussels Midi",
		],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "medium",
		question:
			"In what dialogue did Socrates defend himself to the court of Athens? ",
		correct_answer: "The Apology",
		options: ["The Euthyphro", "The Laws", "The Apology", "The Republic"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "hard",
		question:
			"How many trophies are there in &quot;Super Smash Bros. for Nintendo 3DS&quot;?",
		correct_answer: "685",
		options: ["1155", "1360", "685", "716"],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "medium",
		question: "What was the total length of the Titanic?",
		correct_answer: "882 ft | 268.8 m",
		options: [
			"759 ft | 231.3 m",
			"1042 ft | 317.6 m",
			"825 ft | 251.5 m",
			"882 ft | 268.8 m",
		],
	},
	{
		category: "Geography",
		type: "boolean",
		difficulty: "easy",
		question: "Tokyo is the capital of Japan.",
		correct_answer: "True",
		options: ["False", "True"],
	},
	{
		category: "Entertainment: Video Games",
		type: "multiple",
		difficulty: "hard",
		question:
			"In &quot;Final Fantasy VI&quot;, what is the name of (summoned) Gilgamesh&#039;s weakest attack?",
		correct_answer: "Excalipoor",
		options: ["Excalibore", "Excalipoor", "Excalisnore", "Excalisore"],
	},
	{
		category: "Entertainment: Japanese Anime & Manga",
		type: "multiple",
		difficulty: "medium",
		question:
			"In the &quot;Sailor Moon&quot; series, what is Sailor Jupiter&#039;s civilian name?",
		correct_answer: "Makoto Kino",
		options: ["Usagi Tsukino", "Minako Aino", "Rei Hino", "Makoto Kino"],
	},
	{
		category: "Science: Gadgets",
		type: "multiple",
		difficulty: "hard",
		question:
			"Which of the following cellular device companies is NOT headquartered in Asia?",
		correct_answer: "Nokia",
		options: ["HTC", "Nokia", "Samsung", "LG Electronics"],
	},
	{
		category: "Celebrities",
		type: "multiple",
		difficulty: "medium",
		question: "In what year did &quot;Bob Ross&quot; die?",
		correct_answer: "1995",
		options: ["1997", "1995", "1986", "1989"],
	},
	{
		category: "Entertainment: Film",
		type: "boolean",
		difficulty: "easy",
		question: "Actor Tommy Chong served prison time.",
		correct_answer: "True",
		options: ["False", "True"],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "medium",
		question:
			"On which aircraft carrier did the Doolitte Raid launch from on April 18, 1942 during World War II?",
		correct_answer: "USS Hornet",
		options: ["USS Lexington", "USS Enterprise", "USS Saratoga", "USS Hornet"],
	},
	{
		category: "Entertainment: Board Games",
		type: "multiple",
		difficulty: "hard",
		question:
			"In Magic: The Gathering, what was a tribute card to Jamie Wakefield&#039;s late wife Marilyn, who loved horses?",
		correct_answer: "Timbermare",
		options: [
			"Loyal Pegasus",
			"Vryn Wingmare",
			"Sungrace Pegasus",
			"Timbermare",
		],
	},
	{
		category: "Entertainment: Comics",
		type: "multiple",
		difficulty: "hard",
		question:
			"In 1978, Superman teamed up with what celebrity, to defeat an alien invasion?",
		correct_answer: "Muhammad Ali",
		options: [
			"Muhammad Ali",
			"Arnold Schwarzenegger",
			"Sylvester Stallone",
			"Mike Tyson",
		],
	},
	{
		category: "Sports",
		type: "multiple",
		difficulty: "easy",
		question: "When was the first official international game played?",
		correct_answer: "1872",
		options: ["1863", "1880", "1872", "1865"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "medium",
		question:
			"The &#039;In the Flesh&#039; tour was used in support of what Pink Floyd album?",
		correct_answer: "Animals",
		options: ["Animals", "The Wall", "The Final Cut", "Wish You Were Here"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "hard",
		question:
			"Chino Moreno is the lead singer of which alternative metal band?",
		correct_answer: "Deftones",
		options: ["Type O Negative", "Korn", "Deftones", "Tool"],
	},
	{
		category: "General Knowledge",
		type: "multiple",
		difficulty: "easy",
		question:
			"Terry Gilliam was an animator that worked with which British comedy group?",
		correct_answer: "Monty Python",
		options: [
			"Monty Python",
			"The Goodies&lrm;",
			"The Penny Dreadfuls",
			"The League of Gentlemen&lrm;",
		],
	},
	{
		category: "Animals",
		type: "multiple",
		difficulty: "medium",
		question:
			"What is the common term for bovine spongiform encephalopathy (BSE)?",
		correct_answer: "Mad Cow disease",
		options: [
			"Mad Cow disease",
			"Weil&#039;s disease",
			"Foot-and-mouth disease",
			"Milk fever",
		],
	},
	{
		category: "General Knowledge",
		type: "multiple",
		difficulty: "hard",
		question: "What is the weight of a Gold Bar in Fallout: New Vegas?",
		correct_answer: "35 Pounds",
		options: ["32.50 Pounds", "40 Pounds", "35 Pounds", "30 Pounds"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "medium",
		question: "What was Britney Spears&#039; debut single?",
		correct_answer: "...Baby One More Time",
		options: [
			"Toxic",
			"...Baby One More Time",
			"(You Drive Me) Crazy",
			"Oops!... I Did It Again",
		],
	},
	{
		category: "Animals",
		type: "boolean",
		difficulty: "easy",
		question: "The internet browser Firefox is named after the Red Panda.",
		correct_answer: "True",
		options: ["False", "True"],
	},
	{
		category: "History",
		type: "multiple",
		difficulty: "medium",
		question: "Who was the first Chancellor of a united Germany in 1871? ",
		correct_answer: "Otto Von Bismark",
		options: [
			"Fredrick the 2nd",
			"Otto Von Bismark",
			"Kaiser Wilhelm ",
			"Robert Koch",
		],
	},
	{
		category: "Entertainment: Video Games",
		type: "boolean",
		difficulty: "medium",
		question: "Shang Tsung is a playable character in Mortal Kombat XL.",
		correct_answer: "False",
		options: ["False", "True"],
	},
	{
		category: "Vehicles",
		type: "boolean",
		difficulty: "medium",
		question:
			"The snowmobile was invented by Canadian Joseph-Armand Bombardier in 1937.",
		correct_answer: "True",
		options: ["True", "False"],
	},
	{
		category: "Entertainment: Music",
		type: "multiple",
		difficulty: "medium",
		question:
			"On the cover of &#039;Abbey Road,&#039; which of the Beatles is not wearing shoes?",
		correct_answer: "Paul McCartney",
		options: [
			"John Lennon",
			"George Harrison",
			"Ringo Starr",
			"Paul McCartney",
		],
	},
	{
		category: "Entertainment: Film",
		type: "multiple",
		difficulty: "easy",
		question:
			"Who plays Jack Burton in the movie &quot;Big Trouble in Little China?&quot;",
		correct_answer: "Kurt Russell",
		options: ["Harrison Ford", "John Cusack", "Patrick Swayze", "Kurt Russell"],
	},
];
export default data;
